export const ADMIN_ROUTE = '/admin'
export const DEVICE_ROUTE = '/device'
export const MAINPAGE_ROUTE = '/mainpage'
export const LOGIN_ROUTE = '/login'
export const CART_ROUTE = '/cart'
export const ORDER_ROUTE = '/order'
export const FAVORITES_ROUTE = '/favorites'
export const SEARCH_ROUTE = '/search'
